SetThreadDescription() API is not supported on older windows servers.
odygrd/quill pull request #115
Opened 2021-06-14 15:57 UTC by anluoma

Add QUILL_NO_THREAD_NAME_SUPPORT CMAKE build option to prevent usage of SetThreadDescription API

Use of SetThreadDescription() only works in Windows 2019 server.

Issue (#113)

2021-06-14 17:35 UTC, bl-ue requested changes
A few minor suggestions.

2021-06-14 17:35 UTC, bl-ue commented on CMakeLists.txt
> +option(QUILL_NO_THREAD_NAME_SUPPORT "Disable not supported features on windows 2012/2016" OFF)
```suggestion
option(QUILL_NO_THREAD_NAME_SUPPORT "Disable features that are not supported on Windows 2012/2016" OFF)
```

2021-06-14 17:35 UTC, bl-ue commented on quill/src/detail/misc/Os.cpp
> +  #if defined(__CYGWIN__) || defined(__MINGW32__) || defined(__MINGW64__) || defined(QUILL_NO_THREAD_NAME_SUPPORT)
```suggestion
#if defined(__CYGWIN__) || defined(__MINGW32__) || defined(__MINGW64__) || defined(QUILL_NO_THREAD_NAME_SUPPORT)
```

2021-06-15 13:26 UTC, bl-ue approved these changes

2021-06-16 01:13 UTC, odygrd commented
Thanks for the PR !

2021-06-16 01:14 UTC, merged